-- [Đổi số 25/09/2026] Tên cũ: T38_oqc_daily_inspection.sql (trùng số phase / sai quy ước tên).
--   Nội dung KHÔNG đổi — đã chạy trên staging thì KHÔNG cần chạy lại.
--   Bản vá bảo mật + phân quyền: migration_phase_D61_bao_mat_phan_quyen_iqc_ipqc_oqc_bom_ncp.sql (chạy SAU file này).
-- T38 - Master loi dung chung va phieu OQC kiem tra thanh pham.
alter table public.master_employees add column if not exists ma_nv text;
create unique index if not exists uq_master_employees_ma_nv on public.master_employees(ma_nv) where ma_nv is not null;
create table if not exists public.quality_defect_catalog(id bigserial primary key,code text not null unique,label text not null,defect_group text not null check(defect_group in('NG ngoại quan','NG kích thước','NG khác')),processes text[] not null default array['IQC','OQC','IPQC'],is_active boolean not null default true,sort_order int not null default 100,updated_at timestamptz not null default now());
insert into public.quality_defect_catalog(code,label,defect_group,processes,sort_order) values
('nut','Nứt','NG ngoại quan',array['IQC','OQC','IPQC'],1),('sut','Sứt','NG ngoại quan',array['IQC','OQC','IPQC'],2),('ro_khi','Rỗ khí','NG ngoại quan',array['IQC','OQC','IPQC'],3),('bavia','Bavia','NG ngoại quan',array['OQC','IPQC'],4),('xuoc','Xước','NG ngoại quan',array['IQC','OQC','IPQC'],5),('bong_nhom','Bong nhôm','NG ngoại quan',array['OQC','IPQC'],6),('cong_venh','Cong vênh/biến dạng','NG ngoại quan',array['IQC','OQC','IPQC'],7),('vat_c','Vật C','NG ngoại quan',array['IQC','OQC','IPQC'],8),('nhan','Nhăn','NG ngoại quan',array['OQC','IPQC'],9),('di_vat','Dị vật','NG ngoại quan',array['IQC','OQC','IPQC'],10),('dap_lech','Dập lệch','NG ngoại quan',array['OQC','IPQC'],11),('ga_lech','Gá lệch','NG ngoại quan',array['OQC','IPQC'],12),('va_dap','Va đập','NG ngoại quan',array['IQC','OQC','IPQC'],13),('khong_gia_cong','Không gia công','NG ngoại quan',array['OQC','IPQC'],14),('ng_kich_thuoc','Sai kích thước','NG kích thước',array['IQC','OQC','IPQC'],30),('chat_jig','Chật JIG','NG kích thước',array['IQC','OQC','IPQC'],31),('loi_ren','Thiếu ren/thủng ren','NG kích thước',array['IQC','OQC','IPQC'],32) on conflict(code) do update set label=excluded.label,defect_group=excluded.defect_group,processes=excluded.processes;
do $$begin if to_regclass('public.iqc_appearance_defects') is not null then insert into public.quality_defect_catalog(code,label,defect_group,processes,sort_order) select 'iqc_'||substr(md5(label),1,12),label,'NG ngoại quan',array['IQC','OQC'],100+sort_order from public.iqc_appearance_defects on conflict(code) do nothing;end if;end$$;
create table if not exists public.oqc_daily_inspection(id bigserial primary key,inspection_date date not null,shift text not null,product_code text not null,product_name text not null,inspector_code text not null,inspector_name text not null,total_qty numeric not null check(total_qty>=0),ok_qty numeric not null check(ok_qty>=0),ng_qty numeric not null check(ng_qty>=0),defects jsonb not null default '[]'::jsonb,note text,created_by uuid default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ok_qty+ng_qty=total_qty));
create table if not exists public.oqc_daily_inspection_audit(id bigserial primary key,inspection_id bigint not null references public.oqc_daily_inspection(id),actor_id uuid,actor_name text not null,old_data jsonb,new_data jsonb,changed_at timestamptz not null default now());
alter table public.quality_defect_catalog enable row level security;alter table public.oqc_daily_inspection enable row level security;alter table public.oqc_daily_inspection_audit enable row level security;
drop policy if exists "quality defect read" on public.quality_defect_catalog;create policy "quality defect read" on public.quality_defect_catalog for select using(true);
drop policy if exists "quality defect admin write" on public.quality_defect_catalog;create policy "quality defect admin write" on public.quality_defect_catalog for all to authenticated using(public.has_role('admin','qc_manager')) with check(public.has_role('admin','qc_manager'));
drop policy if exists "oqc inspection read" on public.oqc_daily_inspection;create policy "oqc inspection read" on public.oqc_daily_inspection for select to authenticated using(true);
drop policy if exists "oqc audit read" on public.oqc_daily_inspection_audit;create policy "oqc audit read" on public.oqc_daily_inspection_audit for select to authenticated using(true);
revoke insert,update,delete on public.oqc_daily_inspection,public.oqc_daily_inspection_audit from anon,authenticated;
create or replace function public.oqc_save_daily_inspection(p_id bigint,p_data jsonb,p_actor text) returns bigint language plpgsql security definer set search_path=public as $$declare v_id bigint;v_old jsonb;v_total numeric:=coalesce((p_data->>'total_qty')::numeric,0);v_ng numeric;begin
if auth.uid() is null then raise exception 'Cần đăng nhập MES';end if;select coalesce(sum(coalesce((x->>'qty')::numeric,0)),0) into v_ng from jsonb_array_elements(coalesce(p_data->'defects','[]'::jsonb))x;if v_ng>v_total then raise exception 'Tổng NG chi tiết không được vượt Tổng kiểm';end if;if trim(coalesce(p_data->>'product_code',''))='' or trim(coalesce(p_data->>'inspector_code',''))='' then raise exception 'Thiếu Model hoặc mã nhân viên';end if;if not exists(select 1 from master_products where ma_sp=p_data->>'product_code') then raise exception 'Model không có trong Master';end if;
if p_id is null then insert into oqc_daily_inspection(inspection_date,shift,product_code,product_name,inspector_code,inspector_name,total_qty,ok_qty,ng_qty,defects,note)values((p_data->>'inspection_date')::date,p_data->>'shift',p_data->>'product_code',p_data->>'product_name',p_data->>'inspector_code',coalesce(nullif(p_data->>'inspector_name',''),p_data->>'inspector_code'),v_total,v_total-v_ng,v_ng,p_data->'defects',p_data->>'note')returning id into v_id;
else select to_jsonb(x) into v_old from oqc_daily_inspection x where id=p_id for update;if v_old is null then raise exception 'Không tìm thấy record';end if;update oqc_daily_inspection set inspection_date=(p_data->>'inspection_date')::date,shift=p_data->>'shift',product_code=p_data->>'product_code',product_name=p_data->>'product_name',inspector_code=p_data->>'inspector_code',inspector_name=coalesce(nullif(p_data->>'inspector_name',''),p_data->>'inspector_code'),total_qty=v_total,ok_qty=v_total-v_ng,ng_qty=v_ng,defects=p_data->'defects',note=p_data->>'note',updated_at=now()where id=p_id;v_id:=p_id;insert into oqc_daily_inspection_audit(inspection_id,actor_id,actor_name,old_data,new_data)values(v_id,auth.uid(),p_actor,v_old,(select to_jsonb(x)from oqc_daily_inspection x where id=v_id));end if;return v_id;end$$;
grant execute on function public.oqc_save_daily_inspection(bigint,jsonb,text) to authenticated;
create or replace function public.oqc_audit_immutable()returns trigger language plpgsql as $$begin raise exception 'Lịch sử OQC không được sửa hoặc xóa';end$$;drop trigger if exists trg_oqc_audit_immutable on public.oqc_daily_inspection_audit;create trigger trg_oqc_audit_immutable before update or delete on public.oqc_daily_inspection_audit for each row execute function public.oqc_audit_immutable();
