-- ============================================================================
-- Phase S10: danh mục nguyên vật liệu và linh kiện đúc theo bảng thống kê.
-- Chạy trong Supabase SQL Editor trên staging trước khi merge PR vào staging.
-- Chạy lại an toàn: dữ liệu mẫu chỉ thêm mã hệ thống chưa tồn tại.
-- ============================================================================

create table if not exists public.nvl_danh_muc_toyotaki (
  id bigint generated by default as identity primary key,
  nha_cung_cap text not null,
  ten_nvl text not null,
  ma_nvl text not null,
  ma_nvl_toyotaki text not null unique,
  khach_hang text not null default '',
  san_pham text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.nvl_danh_muc_toyotaki enable row level security;
grant select, insert, update, delete on public.nvl_danh_muc_toyotaki to authenticated;
grant usage, select on sequence public.nvl_danh_muc_toyotaki_id_seq to authenticated;

drop policy if exists "admin manage nvl_danh_muc_toyotaki" on public.nvl_danh_muc_toyotaki;
create policy "admin manage nvl_danh_muc_toyotaki" on public.nvl_danh_muc_toyotaki
  for all to authenticated
  using (public.has_role('admin'))
  with check (public.has_role('admin'));

insert into public.nvl_danh_muc_toyotaki
  (nha_cung_cap, ten_nvl, ma_nvl, ma_nvl_toyotaki, khach_hang, san_pham)
values
  ('Daikin', 'Nhôm', 'HD2- ADC12', 'K-NHN-12-001', 'FCC', 'K09,HPH,KFM,Pressure'),
  ('Chiến thắng', 'Nhôm', 'ADC 12', 'K-NHN-12-002', 'Exedy,Ghế okaya,TTI', 'Center/plat/pply/ outer'),
  ('Tân Quang', 'Nhôm', 'ADC 12', 'K-NHN-12-003', 'Khác', '9001/9002/8001/8002....'),
  ('Honda trading', 'Nhôm', 'HD2- BS1', 'K-NHN-S1-001', 'ASTEMO, Fomeco', 'Fr'),
  ('Nhôm thái lan', 'Nhôm', 'ADC 12', 'K-NHN-12-004', 'Exedy', 'Center/plat/pply/ outer'),
  ('Honda trading', 'Nhôm', 'ADC 6', 'K-NHN-06-001', 'Iwatani', '118,119'),
  ('Honda trading', 'Kẽm', 'EZDA3', 'K-KEN-A3-001', 'Exedy', '3B54,53,69'),
  ('Metal', 'Kẽm', 'EZDA3-Metal', 'K-KEN-A3-002', 'Bảo Phương', '3B54,53,69'),
  ('Astemo', 'Pin Brake', '008-D39-117', 'C-PIN-39-001', 'Astemo', 'Fr'),
  ('Astemo', 'Sleev Brake', '008-D19-126', 'C-BAC-19-001', 'Astemo', 'Fr'),
  ('Việt pháp', 'Ống nhôm phía ngoài S', '27L024 - 002P01', 'C-ONN-OS-001', 'Ghế okaya', 'Ghế okaya'),
  ('Việt pháp', 'Ống nhôm phía ngoài L', '27L025 - 001P01', 'C-ONN-OL-001', 'Ghế okaya', 'Ghế okaya'),
  ('Việt pháp', 'Ống nhôm phía ngoài LL', '27L026 - 001P01', 'C-ONN-LL-001', 'Ghế okaya', 'Ghế okaya'),
  ('Việt pháp', 'Ống nhôm phía ngoài SS', '27L031 - 003P01', 'C-ONN-SS-001', 'Ghế okaya', 'Ghế okaya'),
  ('Việt pháp', 'Ống nhôm phía ngoài S (Không đục lỗ)', '27L024 - 002P01A', 'C-ONN-OS-002', 'Ghế okaya', 'Nòng khuôn'),
  ('Việt pháp', 'Ống nhôm phía ngoài L (Không đục lỗ)', '27L025 - 001P01A', 'C-ONN-OL-002', 'Ghế okaya', 'Nòng khuôn'),
  ('Việt pháp', 'Ống nhôm phía ngoài LL (Không đục lỗ)', '27L026 - 001P01A', 'C-ONN-LL-002', 'Ghế okaya', 'Nòng khuôn'),
  ('Việt pháp', 'Ống nhôm phía ngoài SS (Không đục lỗ)', '27L031 - 002P01A', 'C-ONN-SS-002', 'Ghế okaya', 'Nòng khuôn'),
  ('Việt pháp', 'Ống nhôm phía Trong S', '0395049-249', 'C-ONT-OS-001', 'Ghế okaya', 'Ghế okaya'),
  ('Việt pháp', 'Ống nhôm phía Trong L', '0395049-250', 'C-ONT-OL-001', 'Ghế okaya', 'Ghế okaya'),
  ('Việt pháp', 'Ống nhôm phía Trong LL', '0395049-251', 'C-ONT-LL-001', 'Ghế okaya', 'Ghế okaya'),
  ('BRT/Ming ann', 'Chốt kim loại', '0395049-229', 'C-CKL-29-001', 'Ghế okaya', 'Xuất khẩu'),
  ('Thời Đại', 'Sơn bột tĩnh điện', 'EA212-80', 'S-BOT-TR-002', 'Ghế okaya', 'Ghế okaya'),
  ('Thời Đại', 'Sơn bột tĩnh điện', 'EA11129', 'S-BOT-TR-001', 'SVP', 'Lock, Bản lề, đinh vít'),
  ('Thời Đại', 'Sơn bột tĩnh điện', 'ME010V', 'S-BOT-CA-001', 'Iwatani', '114')
on conflict (ma_nvl_toyotaki) do nothing;