// Offline behavior tests of the current staging pages; all APIs/storage are mocked.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),cp=require('node:child_process');
const {JSDOM}=require(process.env.MES_JSDOM_PATH||'jsdom');
const read=f=>fs.readFileSync(f,'utf8');
const job={id_dong:'JOB-A',ma_may:'DC6',ma_sp:'MODEL-A',row_seq:2,ngay:'2026-10-08',ca:'Ca ngày',sp_start_time:'2026-10-08T00:00:00Z',tt_ca:50};
const checkpoint={id_checkpoint:'CP-A',id_dong:job.id_dong,ma_may:job.ma_may,ma_sp:job.ma_sp,ngay:job.ngay,ca:job.ca,loai_kiem:'doi_khuon',trang_thai:'cho_kiem',ket_qua:null,ghi_chu:'Lỗi xước'};
function database(options={}){
  const tables={duc_ca_hien_tai:[{...job}],duc_bao_cao_ca:[],duc_ipqc_checkpoint:[{...checkpoint}],duc_ipqc_tieuchuan:[{ma_sp:job.ma_sp,file_pdf_url:'https://example.invalid/spec.pdf',danh_sach_muc_kiem_json:['Only reference data']}],duc_ipqc_continue_request:[],duc_ipqc_continue_audit:[],
    master_products:[{ma_sp:job.ma_sp,ten_sp:'Model A'}],master_employees:[{ma_nv:'NV01',ten_nhan_vien:'Inspector',vai_tro:'oqc'}],user_roles:[{user_id:'u1',username:'NV01',full_name:'Inspector',role:options.role||'ipqc'}],
    quality_defect_catalog:[{code:'xuoc',label:'Xước',defect_group:'NG ngoại quan',processes:['OQC'],is_active:true,sort_order:1},{code:'khac_chuan',label:'Lỗi khác chuẩn',defect_group:'NG khác',processes:['OQC'],is_active:true,sort_order:2}],oqc_daily_inspection:[],...options.tables};
  const calls=[],uploads=[],hub=options.broadcastHub||[];
  const db={tables,calls,uploads,failAfterCreate:false,
    channel(name){const listeners=[];const channel={on(type,filter,callback){listeners.push({type,filter,callback});return channel},subscribe(){hub.push({name,listeners});return channel},async send(message){for(const peer of hub)if(peer.name===name)for(const l of peer.listeners)if(l.type==='broadcast'&&l.filter.event===message.event)l.callback({payload:message.payload});return 'ok'}};return channel},
    from(table){let filters=[],range=[0,Infinity],single=false,ordering=null;
      const q={select(){return q},order(key,opts){ordering=[key,opts];return q},eq(key,val){filters.push(row=>row[key]===val);return q},gte(key,val){filters.push(row=>row[key]>=val);return q},lte(key,val){filters.push(row=>row[key]<=val);return q},contains(key,val){filters.push(row=>Array.isArray(val)?val.every(v=>row[key]?.includes(v)):Object.entries(val).every(([k,v])=>row[key]?.[k]===v));return q},in(key,val){filters.push(row=>val.includes(row[key]));return q},range(a,b){range=[a,b];return q},limit(n){range=[0,n-1];return q},maybeSingle(){single=true;return q},
        then(resolve,reject){if(table==='duc_ipqc_tieuchuan'&&options.standardError)return Promise.resolve({data:null,error:{message:'Reference offline'}}).then(resolve,reject);let rows=(tables[table]||[]).filter(row=>filters.every(filter=>filter(row)));if(ordering){const [key,opts]=ordering;rows=[...rows].sort((a,b)=>String(a[key]??'').localeCompare(String(b[key]??''))*(opts?.ascending===false?-1:1));}rows=rows.slice(range[0],range[1]===Infinity?undefined:range[1]+1);return Promise.resolve({data:single?rows[0]||null:rows,error:null}).then(resolve,reject);}
      };return q;},
    async rpc(name,args){calls.push({name,args});if(name==='duc_submit_ipqc_check'){const row=tables.duc_ipqc_checkpoint.find(c=>c.id_checkpoint===args.p_id_checkpoint);Object.assign(row,{ket_qua:args.p_ket_qua,trang_thai:'da_kiem',ghi_chu:args.p_ghi_chu,anh_bang_chung_url:args.p_anh_urls,checklist_json:args.p_checklist,nguoi_kiem:args.p_nguoi_kiem,thoi_diem_kiem_thuc_te:'2026-10-08T03:00:00Z'});if(db.failAfterCheck){db.failAfterCheck=false;return {data:null,error:{message:'Response lost after saved warning'}};}return {data:{ok:true},error:null};}
      if(name==='duc_ipqc_create_continue_request'){const id=tables.duc_ipqc_continue_request.length+1;tables.duc_ipqc_continue_request.push({id,requester_id:'u1',status:'Chờ duyệt',current_step:1,created_at:'2026-10-08T03:00:00Z',...args.p_data});tables.duc_ipqc_continue_audit.push({request_id:id,action:'TẠO YÊU CẦU',detail:args.p_data});if(db.failAfterCreate){db.failAfterCreate=false;return {data:null,error:{message:'Response lost after database accepted request'}};}return {data:id,error:null};}
      if((name==='oqc_save_daily_inspection'||name==='oqc_save_daily_inspection_qc_v2')){const d=args.p_data,ng=d.defects.reduce((n,x)=>n+Number(x.qty),0),row={...tables.oqc_daily_inspection.find(r=>r.id===args.p_id),...d,id:args.p_id||tables.oqc_daily_inspection.length+1,ng_qty:ng,ok_qty:d.total_qty-ng,created_at:'2026-10-08T12:00:00Z'};const index=tables.oqc_daily_inspection.findIndex(r=>r.id===args.p_id);if(index<0)tables.oqc_daily_inspection.push(row);else tables.oqc_daily_inspection[index]=row;return {data:row.id,error:null};}
      return {data:name==='duc_get_ipqc_periodic_due'?[]:null,error:null};},
    storage:{from(){return {async upload(path,blob,opts){uploads.push({path,blob,opts});return {error:null}},getPublicUrl(path){return {data:{publicUrl:'https://example.invalid/evidence/'+path}}}};}}
  };return db;
}
function page(file,options={}){
  const dom=new JSDOM(read(file),{url:'https://mes-toyotaki.dangnaf.workers.dev/'+file,runScripts:'outside-only'}),w=dom.window,context=dom.getInternalVMContext(),db=database(options);
  w.sb=db;w.MesAuth={getSession:async()=>({user:{id:'u1',email:'unused@example.invalid'}}),requireAuth:async()=>({user:{id:'u1'}}),getCurrentUserIdentity:async()=>'NV01_Inspector'};w.MesNav={setTitle(){}};
  w.setInterval=()=>0;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.alerts=[];w.alert=s=>w.alerts.push(s);w.prompt=()=>null;w.CSS={escape:s=>String(s).replace(/[^\w-]/g,'')};
  w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'))};
  const add=w.addEventListener.bind(w);w.addEventListener=(event,...args)=>{if(event!=='load')add(event,...args);};
  w.exported=null;w.XLSX={utils:{json_to_sheet:rows=>{w.exported=rows;return {}},book_new:()=>({}),book_append_sheet(){}},writeFile(){}};
  const run=source=>new vm.Script(source).runInContext(context);
  for(const script of read(file).matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){
    const src=/\bsrc="([^"]+)"/.exec(script[1]);if(src){const clean=src[1].split('?')[0];if(clean.startsWith('shared/')&&!['shared/supabase-client.js','shared/navbar.js'].includes(clean))run(read(clean));}else run(script[2]);
  }
  return {dom,w,db,run};
}
const wait=()=>new Promise(r=>setTimeout(r,25));
let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
function originalFunction(text,name){const index=text.indexOf('function '+name+'(');assert.ok(index>=0,name);const end=text.indexOf('\n}',index);return text.slice(index,end+2).replace(/\r/g,'');}
async function inspect(p){p.run('state.queue='+JSON.stringify([{...checkpoint}]));await p.w.openCheck(checkpoint.id_checkpoint);}
function warningInputs(p){p.run("state.checklistAnswers.find(a=>a.code==='machine_condition').dat=true");p.run("state.photos=[{blob:new Blob(['photo'],{type:'image/jpeg'}),mime:'image/jpeg',dataUrl:'data:image/jpeg;base64,AA=='}]");p.w.setChecklistAnswer(0,false);p.w.document.getElementById('ck-ghi-chu').value='Xước ngoại quan';}
async function oqcInputs(p){await wait();const e=id=>p.w.document.getElementById(id);e('date').value='2026-10-06';e('code').value=job.ma_sp;e('code').dispatchEvent(new p.w.Event('change'));e('inspectorCode').value='NV01';e('inspectorCode').dispatchEvent(new p.w.Event('change'));e('total').value='20';e('total').dispatchEvent(new p.w.Event('input'));return e;}
(async()=>{
  await test('edited scripts and all inline page scripts parse',()=>{for(const f of ['shared/mes-ipqc-flow.js','shared/mes-ipqc-warning.js','shared/mes-ipqc-approval.js','shared/mes-oqc-record.js'])new vm.Script(read(f));for(const f of ['ipqc.html','ipqc-approval.html','oqc-daily.html','sanluong-supabase.html'])for(const m of read(f).matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g))if(!m[1].includes('src='))new vm.Script(m[2]);});
  await test('current IPQC checklist, photos, queue and machine-condition functions preserved',()=>{const old=cp.execFileSync('git',['show','HEAD:ipqc.html'],{encoding:'utf8'}),now=read('ipqc.html');for(const name of ['setChecklistAnswer','onPhotoSelected','removePhoto','renderPhotoGrid','uploadEvidencePhotos','loadIncidentInfo',...[...old.matchAll(/function (\w*Queue\w*)\(/g)].map(m=>m[1])])assert.equal(originalFunction(now,name),originalFunction(old,name),name);assert.ok(now.includes('p_ghi_chu: ghiChu'));});
  await test('standard data never replaces original checklist; PDF preserves selected answers',async()=>{const p=page('ipqc.html');await inspect(p);const base=JSON.parse(p.run('JSON.stringify(IPQC_DEFAULT_CHECKLIST)'));assert.deepEqual(JSON.parse(p.run('JSON.stringify(state.checklistAnswers.filter(a=>a.code!=="machine_condition").map(a=>a.muc))')),base);p.w.setChecklistAnswer(0,true);const before=p.run('JSON.stringify(state.checklistAnswers)');p.w.document.getElementById('ck-pdf-btn').click();assert.ok(p.w.document.querySelector('dialog[open] iframe'));p.w.document.querySelector('dialog[open] iframe').parentElement.querySelector('button').click();assert.equal(p.run('JSON.stringify(state.checklistAnswers)'),before);p.dom.window.close();});
  await test('missing or unavailable standards still allow original checklist',async()=>{for(const options of [{tables:{duc_ipqc_tieuchuan:[]}},{standardError:true}]){const p=page('ipqc.html',options);await inspect(p);assert.equal(p.run('state.checklistAnswers.length'),p.run('IPQC_DEFAULT_CHECKLIST.length+1'));assert.equal(p.w.document.getElementById('ck-pdf-btn').disabled,true);p.dom.window.close();}});
  await test('explicitly different-process standard is not opened for IPQC',async()=>{const p=page('ipqc.html',{tables:{duc_ipqc_tieuchuan:[{ma_sp:job.ma_sp,cong_doan:'OQC',file_pdf_url:'https://example.invalid/oqc.pdf'}]}});await inspect(p);assert.equal(p.w.document.getElementById('ck-pdf-btn').disabled,true);p.dom.window.close();});
  await test('OK and NG evidence/checklist validations remain enforced',async()=>{const p=page('ipqc.html');await inspect(p);await p.w.submitCheck('OK');assert.equal(p.db.calls.length,0);p.run("state.photos=[{blob:new Blob(['x']),mime:'image/jpeg'}]");await p.w.submitCheck('OK');assert.equal(p.db.calls.length,0);p.w.setChecklistAnswer(0,false);await p.w.submitCheck('NG');assert.equal(p.db.calls.length,0);p.dom.window.close();});
  await test('one click saves warning and evidence once without a dialog or production request',async()=>{const p=page('ipqc.html');await inspect(p);warningInputs(p);await Promise.all([p.run('MesIpqcWarning.open()'),p.run('MesIpqcWarning.open()')]);assert.equal(p.db.calls.filter(c=>c.name==='duc_submit_ipqc_check').length,1);assert.equal(p.db.calls.filter(c=>c.name==='duc_ipqc_create_continue_request').length,0);assert.equal(p.db.uploads.length,1);const saved=p.db.tables.duc_ipqc_checkpoint[0];assert.equal(saved.ket_qua,'CANH_BAO');assert.equal(saved.nguoi_kiem,'NV01_Inspector');assert.equal(saved.anh_bang_chung_url.length,1);assert.equal(p.w.document.getElementById('warningRequestDialog'),null);assert.equal(p.w.document.getElementById('warningReason'),null);assert.equal(p.run('state.current'),null);p.dom.window.close();});
  await test('lost warning response is confirmed automatically without a second click or duplicate upload',async()=>{const p=page('ipqc.html');await inspect(p);warningInputs(p);p.db.failAfterCheck=true;await p.run('MesIpqcWarning.open()');assert.equal(p.db.tables.duc_ipqc_checkpoint[0].ket_qua,'CANH_BAO');assert.equal(p.run('state.current'),null);await p.run('MesIpqcWarning.open()');assert.equal(p.db.calls.filter(c=>c.name==='duc_submit_ipqc_check').length,1);assert.equal(p.db.calls.filter(c=>c.name==='duc_ipqc_create_continue_request').length,0);assert.equal(p.db.uploads.length,1);assert.equal(p.run('state.current'),null);p.dom.window.close();});
  await test('paired jobs preserved; latest empty row does not select older product',async()=>{const p=page('ipqc.html');assert.deepEqual(JSON.parse(p.run('JSON.stringify(MesIpqcFlow.active('+JSON.stringify([{...job,khuon_kep_voi:'B'},{...job,id_dong:'B',ma_sp:'OTHER',row_seq:1}])+',[]).map(r=>r.id_dong))')),['JOB-A','B']);assert.equal(p.run('MesIpqcFlow.active('+JSON.stringify([job,{...job,id_dong:'NEW',ma_sp:'',row_seq:3}])+',[]).length'),0);p.dom.window.close();});
  await test('stale production job blocks saving warning for a changed model',async()=>{const p=page('ipqc.html');await inspect(p);warningInputs(p);p.db.tables.duc_ca_hien_tai[0].ma_sp='CHANGED';await p.run('MesIpqcWarning.open()');assert.equal(p.db.calls.filter(c=>c.name==='duc_submit_ipqc_check'||c.name==='duc_ipqc_create_continue_request').length,0);p.dom.window.close();});
  await test('direct approval selector fills exact running job, optional LOT and no guessed Task',async()=>{const p=page('ipqc-approval.html',{role:'nhan_vien_duc'});await wait();const e=id=>p.w.document.getElementById(id);e('directProposal').click();e('proposalCountermeasure').value='100% sorting';e('proposalDepartment').value='Production';e('runningJob').value=job.id_dong;e('runningJob').dispatchEvent(new p.w.Event('change'));await wait();assert.equal(e('machine').value,'DC6');assert.equal(e('productCode').value,job.ma_sp);assert.equal(e('process').value,'Đúc');assert.equal(e('lotNo').value,'');assert.equal(e('lotNo').required,false);assert.equal(e('taskNo').value,'');e('warningContent').value='Ngoại quan';e('reasonDetail').value='Lý do';e('timeMode').value='hours';e('allowedHours').value='1';e('requestForm').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await wait();assert.equal(p.db.tables.duc_ipqc_continue_request.length,1);assert.equal(p.db.tables.duc_ipqc_continue_request[0].id_dong,'JOB-A');p.dom.window.close();});
  await test('ordinary account cannot approve; existing manager step roles preserved',async()=>{const request={id:1,requester_id:'other',status:'Chờ duyệt',current_step:1,reason_type:'TIME',duc_ipqc_continue_approval:[]};const p=page('ipqc-approval.html',{tables:{duc_ipqc_continue_request:[request]}});await wait();assert.equal(p.w.document.querySelectorAll('#requests .approve,#requests .reject,#requests .override').length,0);await p.w.decide(1,'Duyệt');assert.equal(p.db.calls.filter(c=>c.name==='duc_ipqc_decide_continue_request').length,0);assert.equal(p.run("MesIpqcFlow.canDecide('qc_manager',1)"),true);assert.equal(p.run("MesIpqcFlow.canDecide('qc_manager',2)"),false);assert.equal(p.run("MesIpqcFlow.canDecide('giam_doc_sx',1,true)"),true);p.dom.window.close();});
  await test('warning appears in approval inbox with inspector time details and photos, without any request',async()=>{const warning={...checkpoint,ket_qua:'CANH_BAO',trang_thai:'da_kiem',nguoi_kiem:'NV01_Inspector',thoi_diem_kiem_thuc_te:'2026-10-09T03:00:00Z',ghi_chu:'<img onerror=bad()>',checklist_json:[{muc:'Scratch',dat:false}],anh_bang_chung_url:['https://example.invalid/warning.jpg']};const p=page('ipqc-approval.html',{tables:{duc_ipqc_checkpoint:[warning]}});await wait();const tbody=p.w.document.getElementById('warningInbox');assert.ok(tbody.textContent.includes('CÓ CẢNH BÁO - CHƯA CÓ ĐỀ NGHỊ TIẾP TỤC SX'));assert.ok(tbody.textContent.includes('NV01_Inspector'));assert.ok(tbody.textContent.includes('Scratch'));assert.equal(tbody.querySelectorAll('[onerror]').length,0);assert.equal(tbody.querySelectorAll('img').length,1);assert.equal(p.db.calls.filter(c=>c.name==='duc_ipqc_create_continue_request').length,0);[...tbody.querySelectorAll('button')].find(b=>b.textContent==='Xem cảnh báo').click();assert.equal(p.w.document.getElementById('warningDetailDialog').open,true);assert.equal(p.w.document.getElementById('proposalPanel').classList.contains('hidden'),true);assert.equal(p.w.document.getElementById('directProposal').hidden,true);p.dom.window.close();});
  await test('production opens exact warning then submits scoped proposal, preserving original warning and evidence',async()=>{const warning={...checkpoint,ket_qua:'CANH_BAO',trang_thai:'da_kiem',nguoi_kiem:'Inspector',thoi_diem_kiem_thuc_te:'2026-10-09T03:00:00Z',checklist_json:[{muc:'Scratch',dat:false}],anh_bang_chung_url:['https://example.invalid/warning.jpg']};const p=page('ipqc-approval.html',{role:'nhan_vien_duc',tables:{duc_ipqc_checkpoint:[warning]}});await wait();const before=JSON.stringify(p.db.tables.duc_ipqc_checkpoint);const button=[...p.w.document.querySelectorAll('#warningInbox button')].find(b=>b.textContent==='ĐỀ NGHỊ TIẾP TỤC SẢN XUẤT');assert.ok(button);button.click();await wait();const e=id=>p.w.document.getElementById(id);assert.equal(e('checkpointId').value,'CP-A');assert.equal(e('runningJob').disabled,true);assert.equal(e('warningCheckpoint').disabled,true);assert.equal(e('warningContent').readOnly,true);assert.equal(e('proposalPanel').classList.contains('hidden'),false);assert.equal(p.db.tables.duc_ipqc_continue_request.length,0);e('reasonDetail').value='Complete order';e('proposalCountermeasure').value='100% sorting';e('proposalDepartment').value='Đúc';e('proposalNote').value='Notify supervisor';e('timeMode').value='hours';e('allowedHours').value='1';e('requestForm').dispatchEvent(new p.w.Event('submit',{cancelable:true}));e('requestForm').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await wait();assert.equal(p.db.tables.duc_ipqc_continue_request.length,1);const request=p.db.tables.duc_ipqc_continue_request[0];assert.equal(request.checkpoint_id,'CP-A');assert.equal(request.id_dong,'JOB-A');assert.equal(request.temporary_countermeasure,'100% sorting');assert.equal(request.requester_department,'Đúc');assert.equal(request.inspection_by,'Inspector');assert.equal(request.inspection_evidence_urls.length,1);assert.equal(JSON.stringify(p.db.tables.duc_ipqc_checkpoint),before);assert.equal(e('warningInbox').textContent.includes('CP-A'),false);p.dom.window.close();});
  await test('IPQC cannot send production proposal through the UI and old linked warnings do not reappear',async()=>{const warning={...checkpoint,ket_qua:'CANH_BAO',trang_thai:'da_kiem'};const p=page('ipqc-approval.html',{tables:{duc_ipqc_checkpoint:[warning],duc_ipqc_continue_request:[{id:3,checkpoint_id:'CP-A',status:'Từ chối',duc_ipqc_continue_approval:[]}]}});await wait();assert.equal(p.w.document.getElementById('warningInbox').textContent.includes('CP-A'),false);p.w.document.getElementById('requestForm').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await wait();assert.equal(p.db.calls.filter(c=>c.name==='duc_ipqc_create_continue_request').length,0);p.dom.window.close();});
  await test('historical warning remains visible but cannot be attached to a newer model on the same machine',async()=>{const warning={...checkpoint,ket_qua:'CANH_BAO',trang_thai:'da_kiem'};const p=page('ipqc-approval.html',{role:'nhan_vien_duc',tables:{duc_ipqc_checkpoint:[warning],duc_ca_hien_tai:[{...job,ma_sp:'NEW-MODEL',id_dong:'JOB-B'}]}});await wait();assert.ok(p.w.document.getElementById('warningInbox').textContent.includes('CP-A'));[...p.w.document.querySelectorAll('#warningInbox button')].find(b=>b.textContent==='ĐỀ NGHỊ TIẾP TỤC SẢN XUẤT').click();await wait();assert.equal(p.w.document.getElementById('proposalPanel').classList.contains('hidden'),true);assert.equal(p.db.tables.duc_ipqc_continue_request.length,0);p.dom.window.close();});
  await test('saved warning reaches another open approval screen immediately through broadcast, with no request creation',async()=>{const hub=[],p=page('ipqc.html',{broadcastHub:hub});const approval=page('ipqc-approval.html',{broadcastHub:hub,tables:p.db.tables});await wait();assert.equal(approval.w.document.getElementById('warningInbox').textContent.includes('CP-A'),false);await inspect(p);warningInputs(p);await p.run('MesIpqcWarning.open()');await wait();assert.ok(approval.w.document.getElementById('warningInbox').textContent.includes('CP-A'));assert.equal(p.db.tables.duc_ipqc_continue_request.length,0);p.dom.window.close();approval.dom.window.close();});
  await test('OQC repeated other-defect rows save once each and calculate NG/%NG correctly',async()=>{const p=page('oqc-daily.html'),e=await oqcInputs(p);const standard=p.w.document.querySelector('#defects .defect');standard.value='2';standard.dispatchEvent(new p.w.Event('input'));e('addOtherDefect').click();e('addOtherDefect').click();const extra=[...e('otherDefects').children];for(const [index,row] of extra.entries()){const name=row.querySelector('[data-other="label"]'),qty=row.querySelector('[data-other="qty"]');name.value='Lỗi thêm '+index;name.dispatchEvent(new p.w.Event('input',{bubbles:true}));qty.value=String(index+3);qty.dispatchEvent(new p.w.Event('input',{bubbles:true}));}assert.equal(e('ng').value,'9');assert.equal(e('ok').value,'11');assert.equal(e('ngPct').value,'45%');e('form').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await wait();const saved=p.db.tables.oqc_daily_inspection[0];assert.equal(saved.defects.length,3);assert.equal(saved.ng_qty,9);assert.equal(saved.inspection_date,'2026-10-06');p.dom.window.close();});
  await test('removing an other-defect row recomputes NG without losing standard rows',async()=>{const p=page('oqc-daily.html'),e=await oqcInputs(p);p.run("MesOqcRecord.add({label:'A',qty:3});MesOqcRecord.add({label:'B',qty:4})");assert.equal(e('ng').value,'7');e('otherDefects').querySelector('[data-remove-other]').click();assert.equal(e('ng').value,'4');assert.equal(p.w.document.querySelectorAll('#defects .defect').length,2);p.dom.window.close();});
  await test('OQC edit keeps original inspection date and retired/duplicate defects and image metadata',async()=>{const row={id:7,inspection_date:'2026-10-06',created_at:'2026-10-08T12:00:00Z',shift:'Ca 1',product_code:job.ma_sp,product_name:'Model A',inspector_code:'NV01',inspector_name:'Inspector',total_qty:20,ng_qty:9,ok_qty:11,defects:[{code:'xuoc',label:'Xước',group:'NG ngoại quan',qty:2,detail:'A'},{code:'retired',label:'Lỗi cũ',group:'NG khác',qty:3,detail:'B',images:['https://example.invalid/old.jpg']},{code:'xuoc',label:'Xước bổ sung',group:'NG ngoại quan',qty:4,detail:'C'}]};const p=page('oqc-daily.html',{tables:{oqc_daily_inspection:[row]}});await wait();p.w.editRow(7);assert.equal(p.w.document.getElementById('date').readOnly,true);assert.equal(p.w.document.getElementById('ng').value,'9');p.w.document.getElementById('date').value='2026-10-08';p.w.document.getElementById('form').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await wait();const saved=p.db.tables.oqc_daily_inspection[0];assert.equal(saved.inspection_date,'2026-10-06');assert.equal(saved.defects.length,3);assert.equal(saved.ng_qty,9);assert.equal(saved.defects.find(d=>d.code==='retired').images[0],'https://example.invalid/old.jpg');p.dom.window.close();});
  await test('OQC history uses inspection date; detail opens read-only with defects/photos and closes',async()=>{const row={id:8,inspection_date:'2026-10-06',created_at:'2026-10-08T12:00:00Z',shift:'Ca 1',product_code:job.ma_sp,product_name:'Model A',inspector_code:'NV01',inspector_name:'Inspector',total_qty:20,ng_qty:3,ok_qty:17,defects:[{code:'legacy',label:'Lỗi cũ',group:'NG khác',qty:3,images:['https://example.invalid/photo.jpg']}],note:'Ghi chú'};const p=page('oqc-daily.html',{tables:{oqc_daily_inspection:[row]}});await wait();const tr=p.w.document.querySelector('#rows tr');assert.ok(tr.textContent.includes('06/10/2026'));assert.ok(!tr.textContent.includes('08/10/2026'));tr.querySelector('td').click();const dialog=p.w.document.getElementById('oqcRecordDialog');assert.equal(dialog.open,true);assert.ok(dialog.textContent.includes('Lỗi cũ'));assert.ok(dialog.textContent.includes('Chưa ghi nhận'));assert.equal(p.run('editing'),null);dialog.querySelector('img').click();assert.ok(p.w.document.querySelector('dialog.qc02-viewer[open]'));p.w.document.getElementById('oqcRecordClose').click();assert.equal(dialog.open,false);p.dom.window.close();});
  await test('legacy record missing inspection date never uses creation timestamp',async()=>{const p=page('oqc-daily.html');await wait();assert.equal(p.run("MesOqcRecord.date({created_at:'2026-10-08T12:00:00Z'})"),'Chưa có dữ liệu');p.dom.window.close();});
  await test('direct request retry uses audit token to avoid duplicate creation',async()=>{const p=page('ipqc.html');const details={client_request_id:'TOKEN-A',reason_type:'EARLY_WARNING',reason_detail:'Review',warning_content:'Warning'};await p.run('MesIpqcFlow.create('+JSON.stringify(job)+',"",'+JSON.stringify(details)+',"NV01_Inspector",false)');await p.run('MesIpqcFlow.create('+JSON.stringify(job)+',"",'+JSON.stringify(details)+',"NV01_Inspector",false)');assert.equal(p.db.tables.duc_ipqc_continue_request.length,1);p.dom.window.close();});
  await test('coordinated browser tabs create only one request for the same checkpoint',async()=>{const p=page('ipqc.html');p.db.tables.duc_ipqc_checkpoint[0].ket_qua='CANH_BAO';let chain=Promise.resolve();Object.defineProperty(p.w.navigator,'locks',{value:{request(name,send){const result=chain.then(send);chain=result.catch(()=>{});return result;}}});await p.run('Promise.all([1,2].map(()=>MesIpqcFlow.create('+JSON.stringify(job)+',"CP-A",{reason_type:"EARLY_WARNING",reason_detail:"Review",warning_content:"Warning"},"NV01_Inspector")))');assert.equal(p.db.tables.duc_ipqc_continue_request.length,1);p.dom.window.close();});
  await test('my-request filter keeps only authenticated account requests',async()=>{const p=page('ipqc-approval.html',{tables:{duc_ipqc_continue_request:[{id:1,requester_id:'u1',status:'Chờ duyệt',current_step:1,reason_type:'TIME',request_code:'MINE',duc_ipqc_continue_approval:[]},{id:2,requester_id:'other',status:'Chờ duyệt',current_step:1,reason_type:'TIME',request_code:'OTHER',duc_ipqc_continue_approval:[]}]}});await wait();const filter=p.w.document.getElementById('onlyMyRequests');filter.checked=true;filter.dispatchEvent(new p.w.Event('change'));assert.equal(p.w.document.querySelectorAll('#requests tr').length,1);assert.ok(p.w.document.getElementById('requests').textContent.includes('MINE'));assert.ok(!p.w.document.getElementById('requests').textContent.includes('OTHER'));p.dom.window.close();});
  await test('Excel sums repeated defect names without overwriting inspection date or totals',async()=>{const row={id:9,inspection_date:'2026-10-06',created_at:'2026-10-08T12:00:00Z',product_code:job.ma_sp,total_qty:20,ng_qty:9,ok_qty:11,defects:[{label:'Other',qty:3},{label:'Other',qty:4},{label:'Ngày',qty:2}]};const p=page('oqc-daily.html',{tables:{oqc_daily_inspection:[row]}});await wait();p.w.exportExcel();assert.equal(p.w.exported[0].Other,7);assert.equal(p.w.exported[0]['Ngày'],'2026-10-06');assert.equal(p.w.exported[0]['Lỗi: Ngày'],2);assert.equal(p.w.exported[0].NG,9);p.dom.window.close();});
  await test('zero-quantity legacy defect retains image metadata when editing',async()=>{const row={id:10,inspection_date:'2026-10-06',created_at:'2026-10-08T12:00:00Z',product_code:job.ma_sp,shift:'Ca 1',product_name:'Model A',inspector_code:'NV01',inspector_name:'Inspector',total_qty:20,ng_qty:0,ok_qty:20,defects:[{code:'xuoc',label:'Xước',group:'NG ngoại quan',qty:0,images:['https://example.invalid/zero.jpg']}]};const p=page('oqc-daily.html',{tables:{oqc_daily_inspection:[row]}});await wait();p.w.editRow(10);p.w.document.getElementById('form').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await wait();assert.equal(p.db.tables.oqc_daily_inspection[0].defects[0].images[0],'https://example.invalid/zero.jpg');assert.equal(p.db.tables.oqc_daily_inspection[0].ng_qty,0);p.dom.window.close();});
  await test('only authorized additive migration; unrelated shared resources retained',()=>{const changes=cp.execFileSync('git',['diff','--name-only','HEAD'],{encoding:'utf8'}).trim().split('\n');assert.ok(!changes.some(f=>f.startsWith('supabase/')&&f!=='supabase/migration_phase_T73_qc_checks_history_staging.sql'));for(const f of ['oqc.html','shared/qc02-data.js','shared/qc02-view.js','shared/navbar.js','shared/supabase-client.js','bom.html','quan-ly-danh-muc.html'])assert.equal(read(f).replace(/\r/g,''),cp.execFileSync('git',['show','HEAD:'+f],{encoding:'utf8'}).replace(/\r/g,''),f);});
  console.log('TOTAL '+passed+' passed. All APIs mocked; no live database or production writes.');
})().catch(error=>{console.error(error);process.exitCode=1;});
